export enum routePaths {
  login = '/',
  consultant = '/consultor',
  consultantDetails = '/consultor/:id',
  companyDetails = '/empresa/:id',
  company = '/empresa',
  shift = '/empresa/:id/turno',
  productionReport = '/apontamento',
  productionReportDetails = '/apontamento/:id',
  stopping = '/apontamento/:id/paradas',
  stoppingCompany = '/empresa/:companyId/apontamento/:id/paradas',
  waste = '/apontamento/:id/refugos',
  wasteCompany = '/empresa/:companyId/apontamento/:id/refugos',
  stoppingReason = '/empresa/:id/motivos-de-parada',
  responsibleArea = '/empresa/:id/areas-responsaveis',
  workstation = '/empresa/:id/postos-de-trabalho',
  collaborator = '/empresa/:id/colaborador',
  product = '/empresa/:id/produto',
  productionReportCompany = '/empresa/:id/apontamento',
  productionReportDetailsCompany = '/empresa/:companyId/apontamento/:id',
  wasteType = '/empresa/:id/tipos-de-refugo',
  requestCode = '/solicitar-codigo',
  enterCode = '/inserir-codigo',
  changePassword = '/alterar-senha'
}

export const paths = {
  login: '/',
  consultant: '/consultor',
  consultantDetails: (id: number | string): string => `/consultor/${id}`,
  companyDetails: (id: number | string): string => `/empresa/${id}`,
  productionReportDetails: (id: number | string): string => `/apontamento/${id}`,
  productionReportCompany: (id: number | string): string => `/empresa/${id}/apontamento`,
  productionReportDetailsCompany: (id: number | string, companyId: number | string): string =>
    `/empresa/${companyId}/apontamento/${id}`,
  stopping: (id: number | string): string => `/apontamento/${id}/paradas`,
  stoppingCompany: (id: number | string, companyId: number | string): string =>
    `/empresa/${companyId}/apontamento/${id}/paradas`,
  waste: (id: number | string): string => `/apontamento/${id}/refugos`,
  wasteCompany: (id: number | string, companyId: number | string): string =>
    `/empresa/${companyId}/apontamento/${id}/refugos`,
  workstation: (id: number | string): string => `/empresa/${id}/postos-de-trabalho`,
  wasteType: (id: number | string): string => `/empresa/${id}/tipos-de-refugo`,
  collaborator: (id: number | string): string => `/empresa/${id}/colaborador`,
  product: (id: number | string): string => `/empresa/${id}/produto`,
  shift: (id: number | string): string => `/empresa/${id}/turno`,
  responsibleArea: (id: number | string): string => `/empresa/${id}/areas-responsaveis`,
  stoppingReason: (id: number | string): string => `/empresa/${id}/motivos-de-parada`,
  productionReport: '/apontamento',
  company: '/empresa',
  requestCode: '/solicitar-codigo',
  enterCode: '/inserir-codigo',
  changePassword: '/alterar-senha'
};

export const apiPaths = {
  default: '/default',
  login: '/login',
  workstation: '/workstation',
  stopping: '/stopping',
  waste: '/waste',
  productionReport: '/production-reporting',
  shift: '/shift',
  stoppingReason: '/stopping-reason',
  responsibleArea: '/responsible-area',
  measurementUnit: '/measurement-unit',
  product: '/product',
  collaborator: '/collaborator',
  wasteType: '/waste-type',
  company: '/company',
  user: '/user',
  requestCode: '/request-code',
  verifyCode: '/verify-code',
  changePassword: '/change-password'
};
